import 'dart:ui';

import 'package:fintech/utils/AColors.dart';
import 'package:fintech/views/Expenses/expenses-main.dart';
import 'package:fintech/views/HomePage.dart';
import 'package:fintech/views/Ledger/ledger-main.dart';
import 'package:fintech/views/LoginPage.dart';
import 'package:fintech/views/Perform/account-page.dart';
import 'package:fintech/views/Perform/cate-page.dart';
import 'package:fintech/views/Perform/performPage.dart';
import 'package:fintech/views/Perform/unit-page.dart';
import 'package:fintech/views/Perform/vendor-page.dart';
import 'package:fintech/views/Purchases/add_purchases.dart';
import 'package:fintech/views/Purchases/purchase_main.dart';
import 'package:fintech/views/Purchases/purchases_list.dart';
import 'package:fintech/views/Purchases/temp_purchases.dart';
import 'package:fintech/views/Sales/new-sale-view.dart';
import 'package:fintech/views/Sales/newSaleController.dart';
import 'package:fintech/views/Sales/sale-list.dart';
import 'package:fintech/views/Sales/sale-main.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';

import 'views/Stocks/stock-main.dart';

Locale lang = window.locale;
void main() {
  Get.lazyPut(() => SaleController());
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      theme: CustomTheme().getTheme(),
      // navigatorKey: NavigationService.navigatorKey,
      debugShowCheckedModeBanner: false,
      // theme: CustomTheme().getTheme(),
      initialRoute: "/",
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      textDirection: TextDirection.rtl,
      locale: const Locale('ar', 'AR'), // استخدام اللغة العربية كمثال
      supportedLocales: const [
        Locale('ar', 'AR'),
      ],
      // supportedLocales: const [
      //   Locale('ar', ''),
      //   Locale('en', ''),
      // ],
      translations: LocaleString(),
      // locale: lang,
      // localeResolutionCallback: (currentLang, supportLang) {
      //   if (currentLang != null) {
      //     for (Locale locale in supportLang) {
      //       if (locale.languageCode == currentLang.languageCode) {
      //         sharedPreferences.setString("language", currentLang.languageCode);
      //         return currentLang;
      //       }
      //     }
      //   }
      //   return supportLang.first;
      // },
      getPages: pages,
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final int _counter = 0;

  void _incrementCounter() {
    Get.offAll(() => Home());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

const String kLoginPage = '/login';
Transition transition = Transition.leftToRightWithFade;
final List<GetPage> pages = [
  GetPage(
    name: "/login",
    page: () => Login(),
  ),
  GetPage(
    name: "/",
    page: () => Home(),
  ),
  GetPage(
    name: "/home",
    page: () => const MyHomePage(title: "hello"),
  ),
  GetPage(
    name: "/perform",
    page: () => const PerformMain(),
  ),
  GetPage(
    name: "/perform/acc",
    page: () => const AccountPage(),
  ),
  GetPage(
    name: "/perform/vendor",
    page: () => const VendorPage(),
  ),
  GetPage(
    name: "/perform/unit",
    page: () => const UnitPage(),
  ),
  GetPage(
    name: "/perform/cate",
    page: () => const CatePage(),
  ),
  GetPage(
    name: "/purchase",
    page: () => const PurchaseMain(),
  ),
  GetPage(
    name: "/purchase/add",
    page: () => const AddPurchases(),
  ),
  GetPage(
    name: "/purchase/temp",
    page: () => const PurchasesTemp(),
  ),
  GetPage(
    name: "/purchase/list",
    page: () => const PurchasesList(),
  ),
  GetPage(
    name: "/stock",
    page: () => const StockMain(),
  ),
  GetPage(
    name: "/sale",
    page: () => const SaleMain(),
  ),
  GetPage(
    name: "/sale/list",
    page: () => const SaleList(),
  ),
  GetPage(
    name: "/sale/insert",
    page: () => NewSaleView(),
    // page: () => const NewSale(),
  ),
  GetPage(
    name: "/ledger",
    page: () => const LedgerMain(),
  ),
  GetPage(
    name: "/expenses",
    page: () => const ExpensesMain(),
  ),
];

enum Transition {
  fade,
  fadeIn,
  rightToLeft,
  leftToRight,
  upToDown,
  downToUp,
  rightToLeftWithFade,
  leftToRightWithFade,
  zoom,
  topLevel,
  noTransition,
  cupertino,
  cupertinoDialog,
  size,
  circularReveal,
  native,
}

class CustomTheme {
  ThemeData getTheme() {
    return ThemeData(
      fontFamily: 'Arial',
      appBarTheme: AppBarTheme(
        backgroundColor: constPrimaryColor,
        centerTitle: true,
        elevation: 14,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.all(Radius.circular(10)),
          side: BorderSide(color: Colors.white, width: 2),
        ),
      ),
      primaryColor: constPrimaryColor,
      primarySwatch: constPrimarySwatchColor,
      disabledColor: constDisabledColor,
      secondaryHeaderColor: constSecondaryColor,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          primary: constPrimaryColor,
          shadowColor: Colors.grey.withOpacity(0.4),
        ),
      ),
      textTheme: TextTheme(
        button: GoogleFonts.almarai(
          color: Colors.white,
          fontWeight: FontWeight.bold,
        ),
        bodyText1: GoogleFonts.almarai(
          fontWeight: FontWeight.bold,
          color: constPrimaryColor,
        ),
        bodyText2: GoogleFonts.almarai(),
        headline3: GoogleFonts.almarai(
          color: constPrimaryColor,
        ),
        headline6: GoogleFonts.almarai(
          color: constPrimaryColor,
        ),
        headline5: GoogleFonts.almarai(
          color: constPrimaryColor,
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        labelStyle: GoogleFonts.almarai(fontSize: 14),
        floatingLabelStyle: GoogleFonts.almarai(
            color: constPrimaryColor, fontWeight: FontWeight.bold),
        contentPadding: const EdgeInsets.symmetric(horizontal: 20),
        border: const OutlineInputBorder(
            borderRadius: BorderRadius.all(Radius.circular(7))),
        focusedBorder: OutlineInputBorder(
          borderSide: BorderSide(color: constPrimaryColor, width: 1.0),
          borderRadius: BorderRadius.all(Radius.circular(10)),
        ),
      ),
    );
  }
}

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //English Language
        'en': english(),
        // Arabic Language
        'ar': arabic(),
      };

  Map<String, String> english() {
    return {
      'enter-c-code': 'Entre Your Information',
      'account-locked': 'Account Locked from system !',
      'account-management': 'Accounts Management',
      'account-name': 'Account name',
      'account-transaction': 'Account Transaction',
      'agent-code': 'Agent code',
      'agent-mobile': 'Agent mobile',
      'agent-name': 'Agent name',
      'agent-not-found': 'Agent not found',
      'agent-short-code': 'Agent short code',
      'agreement-number': 'Agreement number',
      'amount': 'Amount',
      'amount-paid-to-billing-number': 'Amount will be paid to billing number',
      'amounts-not-same': 'Make sure of total amount',
      'available-package': 'Available package',
      'back': 'Back',
      'balance': 'Balance',
      'bank-balance': 'Bank Balance',
      'bill-payment': 'Bill payment',
      'branch': 'Branch',
      'bulk-deposit': 'Bulk Deposit',
      'bundle': 'Bundle',
      'call-us': 'Call us',
      'cancel': 'Cancel',
      'cancel-desc': 'Do you want to cancel the operation ?',
      'cancel-money': 'Cancel Money Transfer',
      'cancel-transfer': 'Cancel Money Transfer',
      'cash-out': 'Cash Out',
      'cashout-from-agent': 'Cashout from agent',
      'cashout-from-bank': 'Cashout from bank',
      'cash-out-request': 'Cash Out Request',
      'cashout-to-customer': 'Cashout To Customer',
      'choose-language': 'Choose Language',
      'city': 'City',
      'clear-list': 'Clear list',
      'click-import-from-excel': 'Click import from excel',
      'client-id': 'Client\'s Identification Number',
      'client-name': 'Client Name',
      'complete-cashout': 'Complete cashout',
      'completed': 'Completed Successfully',
      'complete-withdrawal': 'Complete Withdrawal',
      'comp-name': 'Company name',
      'comp-register': 'Complete Client Registration',
      'confirm': 'Confirm',
      'credit': 'Credit',
      'current-balance': 'Current Balance',
      'customer-withdrawal': 'Customer Withdrawal',
      'dashboard': 'Dashboard',
      'data-confirm': 'Data Confirmation',
      'data-entry': 'Data Entry',
      'search-for-transfer': "Search for a Transfer",
      'data-show': 'Details',
      'date': 'Date',
      'dates': 'Date',
      'debit': 'Debit',
      'deposit': 'Deposit',
      'deposit-from-agent': 'Deposit from agent',
      'deposit-from-bank': 'Deposit from bank',
      'depositor-name': 'Depositor name',
      'desc': 'Description',
      'description': 'Description',
      'diagrammatic-charts': 'Diagrammatic charts',
      'did-not-received-sms': 'Did not received SMS?',
      'doc-no': 'Document No.',
      'done-successful': 'Done Successful',
      'download-pdf': 'Download PDF',
      'enter-otp-that-sent-to-customer-mobile-number':
          'Enter OTP that sent to customer mobile number',
      'enter-otp-that-sent-to-your-number':
          'You will receive code to confirm your device, please write it down here',
      'enter-otp-that-sent-to-yours-mobile-number':
          'Enter OTP that sent to yours mobile number',
      'enter-pin': 'Enter PIN',
      'enter-valid-name': 'Enter valid name',
      'error-found': 'Error found',
      'error-found-confirm': 'Error found confirm',
      'error-in': 'Error in',
      'error-in-this-number': 'Error in this number',
      'error-nm': 'An Error Occurred ! Try again later.',
      'error-no': 'Error No.',
      'favorite': 'Favorites',
      'favorites': 'Favorites',
      'fee': 'Fee',
      'fee-amount': 'Fee amount',
      'feed-balance': 'Feed balance',
      'file-name': 'File name',
      'finish': 'Finish',
      'from-bank-acc': 'Add Balance',
      'go-to-login': 'Go to Login page',
      'help': 'Help',
      'hide': 'Hide',
      'hide-options': 'Hide options',
      'home': 'Home',
      'hour': 'Hour',
      'immediate-charge': 'Immediate charge',
      'import-data-first': 'Import data first',
      'import-from-excel': 'Import from excel',
      'in-progress': 'Sending ...',
      'internet': 'Internet',
      'invalid-credentials': 'Invalid Mobile Number Or Password!',
      'invalid-data-sent': 'Invalid data sent',
      'land-line-number': 'Landline number',
      'language': 'Language',
      'last-month': 'Last month',
      'last-week': 'Last week',
      'length-must-be-greater-than':
          'Length must be greater than @chars characters',
      'length-must-equal': 'Length must equal @chars characters',
      'load-branch-data': 'Load branch data...',
      'load-city-data': 'Load city data...',
      'load-electricity-company-data': 'Load electricity company data...',
      'load-electricity-region-data': 'Load electricity region data...',
      'loading': 'Loading...',
      'load-operator-data': 'Load operator data...',
      'load-package-data': 'Load package data...',
      'load-water-region-data': 'Load water region data...',
      'loan-amount': 'Loan amount',
      'login': 'Login',
      'login-page': 'Login Page',
      'login-to-rem': 'Login Into remittance',
      'logout': 'Logout',
      'mass-deposit': 'Mass Deposit',
      'max-amount-equal': 'Maximum amount is equal to @amt .',
      'mazaya': 'Mazaya',
      'min-amount-equal': 'Minimum amount is equal to @amt .',
      'minutes': 'Minutes',
      'mobile-no-type': 'Mobile number type',
      'mobile-number': 'Mobile Number',
      'money-transfer': 'Send Remittance',
      'money-transfer-cash': 'Pay Remittance',
      'money-transfer-delete': 'Cancel Remittance',
      'money-transfer-update': 'Update Remittance',
      'name-must-be-4-names': 'Enter quatrain noun',
      'new-client': 'Add New Client',
      'news': 'News',
      'next': 'Next',
      'no': 'No',
      'no-data-found': 'No data found',
      'no-notification-yet': 'No Notification Yet !',
      'not-confirmed': 'Not confirmed',
      'notes': 'Notes',
      'notifications': 'Notifications',
      'no-transactions-yet': 'No transactions yet',
      'no-trans-yet': 'No Transactions yet !',
      'numbers-only': 'Enter numbers only',
      'ok': 'Ok',
      'operator': 'Operator',
      'operators': 'Operators',
      'otp': 'OTP',
      'otp-code': 'OTP code',
      'outstanding-transfer': 'Outstanding Transfer',
      'package': 'Package',
      'package-expire-date': 'Package Expire Date',
      'package-name': 'Package Name',
      'package-price': 'Package Price',
      'package-type': 'Package type',
      'paid-money': 'Paid Money',
      'password': 'Password',
      'pay': 'Pay',
      'pay-bill': 'Pay bill',
      'payment': 'Payment',
      'pay-type': 'Pay type',
      'pin-error': 'PIN error',
      'pre-paid': 'Pre paid',
      'previous': 'Previous',
      'print-date': 'Print date',
      'print-pdf': 'Print PDF',
      'receiver-data': 'Receiver data',
      'receiver-mobile': 'Receiver Mobile',
      'receiver-name': 'Receiver Name',
      'records-count': 'Records count',
      'reference-number': 'Reference number',
      'ref-no': 'Reference',
      'refresh': 'Refresh',
      'refresh-every': 'Refresh every',
      'region': 'Region',
      'remittance-number': 'Express number',
      'rem-no': 'Express number',
      'request-date': 'Request date',
      'required': 'Required!',
      're-register-device-error':
          'You have another device logged in with this account, do you want to replace it?',
      'resend': 'Resend',
      'sabafon': 'Sabafon',
      'same-user-id': 'You can\'t use your mobile.',
      'select-a-company': 'Select a company',
      'select-amount': 'Select amount',
      'select-an-operator': 'Select an operator',
      'select-a-package': 'Select a package',
      'select-a-region': 'Select a region',
      'select-a-currency': 'Select a currency',
      'select-brn': 'Select a branch',
      'select-city': 'Select a city',
      'select-mobile-no-type': 'Select mobile number type',
      'select-package': 'Select package',
      'select-package-amount': 'Select package amount',
      'package-amount': 'Package Amount',
      'select-package-type': 'Select package type',
      'select-pay-type': 'Select pay type',
      'sender-data': 'Sender data',
      'sender-mobile': 'Sender Mobile',
      'sender-name': 'Sender Name',
      'send-money': 'Send Money',
      'send-remittance': 'Send remittance',
      'service-not-active': 'Service not active',
      'services-transaction': 'Services Transaction',
      'setting': 'Setting',
      'short-statement': 'Short Statement',
      'show': 'Show',
      'show-options': 'Show options',
      'smart-charge': 'Smart charge',
      'start-with': 'Field must start with @char',
      'status': 'Status',
      'status-description': 'Status description',
      'subscriber-number': 'Subscriber number',
      'sum': 'Total Amount',
      'sum-amount': 'Total amount',
      'this-week': 'This week',
      'to-agent': 'To Agent',
      'to-bank': 'To Bank',
      'to-bank-acc': 'Transfer To Bank Account',
      'today': 'Today',
      'to-mobile-number': 'Destination\'s Mobile Number',
      'to-new-client': 'To New Client',
      'to-register-client': 'To Registered Client',
      'total-amount': 'Total amount',
      'transactions': 'Transactions',
      'transfer': 'Transfer',
      'transfer-to-agent': 'Transfer To Agent',
      'transfer-to-bank': 'Transfer To Bank',
      'trans-id': 'Remittance ID',
      'try': 'Try',
      'try-in-app-notify': 'Try in app notify',
      'unit': 'Unit',
      'update-client-data': 'Update Client Data',
      'update-transfer': 'Update Money Transfer',
      'updating-data': 'Updating data',
      'version': 'Version',
      'wallet-system': 'Wallet System',
      'week': 'Week',
      'welcome': 'Welcome, ',
      'yemen-mobile': 'Yemen Mobile',
      'yer': 'YER',
      'yes': 'Yes',
      'you': 'YOU',
      'you-must-login-first': 'You must logged in first',
      'your_balance': 'Your Balance',
      'server-conn-err': 'Server Connection Error',
      'session-end': 'Session Time Expired !',
      'unknown-error': 'Unknown Error !',
      'change-password': 'Change Password',
      'new-password-must-different-from-previous-one':
          'Your new password must be different from previous one',
      'old-password': 'Current Password',
      'new-password': 'New Password',
      'confirm-password': 'Confirm Password',
      'password-not-matched': 'Passwords Not Matched',
      'same-passwords': 'New Password and Current Password are the same',
      'change': 'Change',
      'tips': 'Tips',
      'password-instructions': 'Password creation instructions',
      'new-password-hint-1':
          '- The password Length is 6 digits at least and contains letters or numbers.',
      'new-password-hint-2':
          '- The password is not one of the words in the dictionary.',
      'new-password-hint-3': '- It does not contains repeated letters.',
      'new-password-hint-4': '- It should not be used as least of 3 days.',
      'new-password-hint-5':
          '- In case of incorrectly entering the password five times, the account will be frozen.',
      'more': 'More',
      'account-statement': 'Account Statement',
      'enter-dates': 'Please, enter the dates',
      'from-date': 'From Date',
      'to-date': 'To Date',
      'choose': 'Choose',
      'choose-date': 'Choose Date',
      'document-number': 'Document No.',
      'document-type': 'Document Type',
      'page': 'Page',
      'of': 'Of',
      'paid-remittance': 'Money Transfer Receipt',
      'receiver-thumb': 'Receiver Thumb',
      'receiver-sign': 'Receiver Signature',
      'receiver-condition1':
          'I received the above amount and in good condition.',
      'duplicate-error': 'Duplicate operation, Please try again later.',
      'customer-name': 'Customer Name',
      'cash-deposit': 'Cash Deposit',
      'received-from-prefix': 'we received from',
      'received-from-suffix': 'respected',
      'reg-to-customer-wallet-account-no':
          'deposit to customer wallet account number',
      'search-customer': 'Searching for customer',
      'enter-otp': 'Enter Confirmation Code (OTP)',
      'error-when-get-mndtry-flds':
          'An error occurred when getting mandatory fields',
      'contact-system-specialist': 'Contact system specialist',
      'customer-mobile': 'Customer mobile',
      'personal-information': 'Personal information',
      'mobile-no': 'Mobile number',
      'full-name': 'Full name',
      'birth-place': 'Place of Birth',
      'birth-date': 'Date of Birth',
      'address': 'Address',
      'work-information': 'Work information',
      'employer': 'Employer',
      'employer-phone': 'Employer phone',
      'id-information': 'Identification Card information',
      'id-number': 'ID number',
      'id-issue-place': 'ID issue place',
      'id-issue-date': 'ID issue date',
      'id-expire-date': 'ID expire date',
      'attachment': 'Attachment',
      'load-id-front-img': 'Load ID front-side',
      'load-id-back-img': 'Load ID back-side',
      'load-form-img': 'Load form copy',
      'nationality': 'Nationality',
      'province': 'Province',
      'social-states': 'Social states',
      'qualification': 'Qualification',
      'specialization': 'Specialization',
      'occupation': 'Occupation',
      'gender': 'Gender',
      'card-type': 'ID card type',
      'select-option': 'Select option',
      'not-all-attachments-loaded': 'Please load all attachments to continue.',
      'reference-not-found': 'Document reference not found!',
      'load-news-data': 'Load News Data',
      'load-fields-data': 'Load Mandatory Fields Data',
      'load-nationality-data': 'Load Nationality Data',
      'load-provinces-data': 'Load Provinces Data',
      'load-social-state-data': 'Load Social State Data',
      'load-qualification-data': 'Load Qualification Data',
      'load-specialization-data': 'Load Specialization Data',
      'load-occupation-data': 'Load Occupation Data',
      'load-gender-data': 'Load Gender Data',
      'load-id-type-data': 'Load ID Types Data',
      'okay': 'Ok',
      'subscribe-price': 'Subscription Price',
      'remain-balance': 'Remaining Balance',
      'expiry-date': 'Expiry Date',
      'subscription-name': 'Subscription Name',
      'amount-owe': 'Amount Owe',
      'all-rights-reserved': 'All rights reserved',
      'main-services': 'Main Services',
      'other-services': 'Other Services',
      'show-news': 'Show News',
      'request-time-out': 'Request time-out.',
      'server-unreachable': 'Server unreachable.',
      'try-again-later': 'Try again later',
      'send-money-by-network': 'Send Money By Network',
      'network-money-transfer': 'Network Money Transfer',
      'network-name': 'Network Name',
      'select-network': 'Select Network',
      'load-rem-network-data': 'Load Network Data',
      'governorate': 'Governorate',
      'select-governorate': 'Select Governorate',
      'load-net-governorate-data': 'Load Governorate Data',
      'select-region': 'Select Region',
      'load-net-region-data': 'Load Region Data',
      'net-fee': 'Network Commission',
      'update-money-by-network': 'Update Money By Network',
      'network-money-transfer-update': 'Network Money Update',
      'network-send-remittance': 'Network Send Remittance',
      'error-occurred': 'An error has been occurred !',
      'open-balance': 'Opening balance',
      'end-balance': 'Ending balance',
      'remittance-report': 'Remittances Report',
      'sent-remittances': 'Sent remittances',
      'payout-remittances': 'Payout remittances',
      'user-code': 'User Code',
      'received-remittances-report': 'Received Remittances',
      'sent-remittances-report': 'Sent Remittances',
      'remember-me': 'Remember me',
      'Note': 'Note',
      'withdraw-money-by-network': 'Withdraw Money By Network',
      'network-money-withdraw': 'Network Money Withdraw',
      'new-register': 'Register New Customer',
      'refresh-lists': 'Refresh Lists',
      'to-agent-req': 'Transfer To Agent Req.',
      'transfer-to-agent-req': 'Transfer To Agent Request',
      'date-format-dd-mm-yyyy': 'Date format is (DD/MM/YYYY)',
      'not-valid': 'Not Valid',
      'check-mobile': 'Check mobile',
      'mobile-exists': 'Mobile exists',
      'mobile-not-exists': 'Mobile not exists',
      'export-to-excel': 'Export to excel',
      'fee-curr': 'Fee Curr.',
      'rem-curr': 'Currency',
      'personal-id': 'Personal ID',
      'passport': 'Passport',
      'cashout': 'Cashout',
      'cashout-from-prefix': 'We pay to',
      'cashout-from-suffix': 'respected, amount of. donated',
      'cashout-from-customer-wallet-account-no':
          'withdrawal from customer wallet account number',
      'transfer-to-prefix': 'A Transfer has been done to',
      'transfer-to-suffix': 'respected, amount of. donated',
      'transfer-to-customer-wallet-account-no':
          'Transferred to wallet account number',
      'transfer-req-condition':
          '** This operation has not been done until approved from bank.',
      'add-fee': 'Agent add fee',
      'done': 'Done',
      'error': 'Error !',
      'total-amount-for-success-operation':
          'Total amount for success operation',
      'device-registration-complete': 'Device registration complete',
      'please-re-login': 'Please login again',
      'packages': 'Packages',
      'phone': 'Phone',
      'view': 'View',
      'view-rm': 'View remittances',
      'print': 'Print',
      'redundant': 'Redundant',
      'nothings': 'There are no comments',
      'IdType': 'Identity Document',
      'IdType-num': 'Number ID',
      'IdType-sender': 'Sender ID Type',
      'IdType-num-sender': 'Sender ID Number',
      'purpose-send': 'Purpose Send',
      'select-id': 'Select ID',
      'select-purpose': 'Select',
      'report-deposit-withdrawal': 'Deposit Withdrawal Report',
      'deposit-report': 'Deposit Report',
      'withdrawal-report': 'Withdrawal Report',
      'view-report': "View Report",
      'reports': "Reports",
      'account-no': 'Account No',
      'report-payments': 'Paymants Report',
      'service-provider': "Service Provider",
      'beneficiary': 'Beneficiary Phone',
      'select-service-provider': "Select Service Provider",
      'payments-report': "Payments Report",
      'searchByRem': 'Search By Remittance Num',
      'searchByName': 'Search By Name',
      'searchByPhone': 'Search By Phone',
      "paid": 'Paid',
      'change-pin': 'Change PIN',
      'new-pin-must-different-from-previous-one':
          'Your new PIN must be different from previous one',
      "The-numbers-are-not-valid": "The numbers are not valid",
      "The-numbers-are-not-valid-eq-last":
          "The numbers are not valid Old Pin equal New Old",
      'new-pin-hint-1': "1-must be consist of 6 new digits",
      'new-pin-hint-2': "2-must be new Pin not equal to old Pin",
      'new-pin-hint-3': "3-No number should be repeated",
      "old-pin": "Old PIN",
      "new-pin": "New PIN",
      "confirm-pin": "Confirm PIN",
      'pin-instructions': "PIN Instructions",
      "pin-not-matched": "PIN isn't matched",
      "idImgPassport": "Passport Image",
      "not-valid-amount": "Amount is not Valid",
      'transfer-not-found': 'Transfer Not Found',
      "can-not-change-pin": "Can not Change PIN",
      'This-list-cannot-be-skipped-until-the-password-ischanged':
          'This list cannot be skipped until the password is changed',
      "can-not-be-greater-than-30": "Must be Less than 30 ",
      "can-not-set-agent-num": "Can't Set your Agent Number",
      "sum-movement": "Sum Movement",
      "email": "Email",
      "call-center": "Call Center",
      "about-us": "About Us",
      "enter-transfer-inform":
          "Enter the transfer number, the recipient's name,or the recipient's phone number",
      'agent-system': 'Agent System',
      'cancel-money-by-network': "Cancel Money By Network",
      "network-money-cancel": "Network Money Cancel",
      "currency": "Currency",
      'fee-addition': 'Agent Fee',
      "network": "network",
      "transfer-approval": "Approval of remittances",
      "demand": "- Demand",
      'accreditation-confirmation':
          'Do you want to approve the accreditation confirmation?',
      "confirm-approval": "Confirm approval",
      "confirm-approval-cancel": "Confirm Cancel Transfer",
      "none": "None",
      "do-not-have-a-right": "You do not have permission",
      'search-field': 'Search field',
      "financial-service": "Financial Service",
      "load-financial-services": "Load Financial Services",
      "refresh-permissions": "Refresh Permissions",
      'need-approved': 'Done,Still This File Needs Approval',
      'bulk-approval': 'Bulk Approval',
      "internal-reference": "Internal Reference ",
      "commission-report": "Commissions Report",
      "sending": "Sending",
      "continue": "Do you want to continue?",
      "get-trans-num": "You will be approved a Transfer Number ",
      "get-proccess-num": "You will be approved a Process Number",
      "get-data-error": "Get data error occurred !",
      "pay-number": "Payment Number",
      "receipt-payments": "Receipt Of Payment",
      "according-to-this-receipt": "According to this receipt ...",
      "for-benefit-subscriber": "For the benefit of subscriber no",
      "receipt-hand": "This receipt is in his hand",
      'exchange-acc': 'Accounts Exchange',
      "from-currency": "Exchange Currency From",
      "to-currency": "Exchange Currency To",
      "can-change-to-same-curr": "Can't use same Currency",
      "amount-want-exchange": 'The amount to be Exchanged',
      "amount-exchanged": 'Amount Exchanged',
    };
  }

  Map<String, String> arabic() {
    return {
      'add': 'أضافة',
      'sales': 'المبيعات',
      'state': 'الحالة',
      'sale': 'المبيعات',
      'discount': 'الخصم',
      'add-new-sale': 'أضافة فاتورة مبيعات',
      'accounts': 'الحسابات',
      'units': 'الوحدات',
      'cates': 'الاصناف',
      'vendors': 'الموردين',
      'expenses': 'المصاريف',
      'ledger': 'سجل الحركة المالية',
      'qty_in': 'كمية داخلة',
      'qty_out': 'كمية خارجة',
      'home-page': 'صفحة البداية',
      'available': 'المخزون المتوفر',
      'No-available': 'المخزون غير المتوفر',
      'price-list': 'تعديل الاسعار',
      'movement': 'حركة المنتجات',
      'pch-add': 'اضافة مشتريات',
      'add-invoice': 'أضافة الفاتورة',
      'ver-invoice-temp': 'اعتماد فاتورة مؤقتة',
      'vendor': 'مورد',
      'cate': 'الصنف',
      'code': 'الكود',
      'price': 'السعر',
      'qty': 'الكمية',
      'barcode': 'الباركود',
      'update': 'تعديل',
      'delete': 'حذف',
      'name-product': 'اسم المنتج',
      'add-product': 'اضافة منتج',
      'invoice-total': 'اجمالي الفاتورة',
      'select-a-vendor': 'اختر اسم المورد',
      'select-a-cate': 'اختر الصنف',
      'select-a-unit': 'اختر الوحدة',
      'enter-c-code': 'أدخل البيانات',
      'account-locked': 'تم تجميد الحساب من قبل النظام !',
      'account-management': 'إدارة الحسابات',
      'account-name': 'اسم الحساب',
      'account-transaction': 'عمليات المحفظة',
      'agent-code': 'رمز الوكيل',
      'agent-mobile': 'رقم جوال الوكيل',
      'agent-name': 'اسم الوكيل',
      'agent-not-found': 'الوكيل غير موجود',
      'agent-short-code': 'رمز الوكيل',
      'agreement-number': 'رقم الاتفاقية',
      'amount': 'المبلغ',
      'amount-paid-to-billing-number': 'المبلغ سيتم سداده لرقم الفوترة',
      'amounts-not-same': 'إجمالي المبالغ غير متساوي، يرجى التأكد',
      'available-package': 'الباقات المتاحة',
      'back': 'عودة',
      'balance': 'الرصيد الحالي',
      'bank-balance': 'رصيد الحساب البنكي',
      'bill-payment': 'فوترة',
      'branch': 'الفرع',
      'bulk-deposit': 'تحويل جماعي',
      'bundle': 'الباقة',
      'call-us': 'إتصل بنا',
      'cancel': 'إلغاء',
      'cancel-desc': 'هل تريد إلغاء العملية ؟',
      'cancel-money': 'إلغاء حوالة مالية',
      'cancel-transfer': 'إلغاء حوالة مالية',
      'cash-out': 'سحب نقدي',
      'cashout-from-agent': 'سحب نقدي من وكيل',
      'cashout-from-bank': 'سحب نقدي من البنك',
      'cash-out-request': 'طلب سحب نقدي',
      'cashout-to-customer': 'سحب نقدي للعميل',
      'choose-language': 'تغيير اللغة',
      'city': 'المدينة',
      'clear-list': 'إلغاء استيراد الملف',
      'click-import-from-excel': 'إضغط على استيراد من ملف اكسل',
      'client-id': 'رقم هوية العميل',
      'client-name': 'اسم العميل',
      'complete-cashout': 'إكمال سحب نقدي',
      'completed': 'تمت العملية بنجاح',
      'complete-withdrawal': 'إكمال سحب نقدي',
      'comp-name': 'اسم الشركة',
      'comp-register': 'إكمال تسجيل عميل',
      'confirm': 'تأكيد',
      'credit': 'دائن',
      'current-balance': 'الرصيد الحالي',
      'customer-withdrawal': 'سحب نقدي مباشر ',
      'dashboard': 'المخططات',
      'data-confirm': 'تأكيد البيانات',
      'data-entry': 'ادخال البيانات',
      'search-for-transfer': "البحث عن حوالة",
      'data-show': 'التفاصيل',
      'date': 'التاريخ',
      'dates': 'التاريخ',
      'debit': 'مدين',
      'deposit': 'إيداع نقدي',
      'deposit-from-agent': 'إيداع نقدي من وكيل',
      'deposit-from-bank': 'إيداع نقدي من البنك',
      'depositor-name': 'اسم المودع',
      'desc': 'البيان',
      'description': 'البيان',
      'diagrammatic-charts': 'الرسوم البيانية',
      'did-not-received-sms': 'لم تستلم كود التحقق ؟',
      'doc-no': 'رقم الوثيقة',
      'done-successful': 'تمت العملية بنجاح',
      'download-pdf': 'إنزال التقرير PDF',
      'enter-otp-that-sent-to-customer-mobile-number':
          'ادخل كود التحقق OTP المرسل لرقم جوال العميل',
      'enter-otp-that-sent-to-your-number':
          'ادخل كود التحقق OTP المرسل لرقم جوالك لإستكمال عملية تسجيل الجهاز.',
      'enter-otp-that-sent-to-yours-mobile-number':
          'ادخل كود التحقق OTP المرسل لرقم جوالك',
      'enter-pin': 'ادخل الرقم السري PIN',
      'enter-valid-name': 'ادخل اسم صحيح',
      'error-found': 'يوجد خطأ',
      'error-found-confirm': 'يوجد خطأ في البيانات ، هل تريد الاستمرار؟',
      'error-in': 'خطأ في',
      'error-in-this-number': 'خطأ في هذا الرقم',
      'error-nm': 'حدث خطأ ما !',
      'error-no': 'خطأ رقم.',
      'favorite': 'التفضيلات',
      'favorites': 'التفضيلات',
      'fee': 'العمولة',
      'fee-amount': 'مبلغ العمولة',
      'feed-balance': 'تغذية رصيد',
      'file-name': 'اسم الملف',
      'finish': 'انهاء',
      'from-bank-acc': 'تغذية رصيد المحفظة',
      'go-to-login': 'الذهاب لصفحة تسجيل الدخول',
      'help': 'مساعدة',
      'hide': 'إخفاء',
      'hide-options': 'إخفاء الخيارات',
      'home': 'الرئيسية',
      'hour': 'الساعات',
      'immediate-charge': 'شحن فوري',
      'import-data-first': 'يجب استيراد البيانات من ملف اكسل اولا ً',
      'import-from-excel': 'إستيراد من ملف اكسل',
      'in-progress': 'جاري الارسال ...',
      'internet': 'الانترنت',
      'invalid-credentials': 'خطأ في رقم الجوال او كلمة المرور',
      'invalid-data-sent': 'خطأ في البيانات المرسلة',
      'land-line-number': 'رقم الهاتف الثابت',
      'language': 'اللغة',
      'last-month': 'آخر شهر',
      'last-week': 'آخر اسبوع',
      'length-must-be-greater-than': 'طول الحقل يجب ان يكون أكبر من @chars',
      'length-must-equal': 'طول الحقل يجب ان يساوي @chars',
      'load-branch-data': 'تحميل بيانات الفروع...',
      'load-city-data': 'تحميل بيانات المدن...',
      'load-electricity-company-data': 'تحميل بيانات شركات الاتصال...',
      'load-electricity-region-data': 'تحميل بيانات مناطق الكهرباء...',
      'loading': 'جاري التحميل...',
      'load-operator-data': 'تحميل بيانات مشغلي الخدمة...',
      'load-package-data': 'تحميل بيانات الباقات...',
      'load-water-region-data': 'تحميل بيانات مناطق المياه...',
      'loan-amount': 'مبلغ السلفة',
      'login': 'تسجيل الدخول',
      'login-page': 'تسجيل الدخول',
      'login-to-rem': 'تسجيل الدخول لنظام الحوالات',
      'logout': 'تسجيل الخروج',
      'mass-deposit': 'تحويل جماعي',
      'max-amount-equal': 'أعلى قيمة يمكن إدخالها @amt .',
      'mazaya': 'مزايا',
      'min-amount-equal': 'اقل قيمة يمكن إدخالها @amt .',
      'minutes': 'دقائق',
      'mobile-no-type': 'نوع رقم الجوال',
      'mobile-number': 'رقم الجوال',
      'money-transfer': 'ارسال حوالة مالية',
      'money-transfer-cash': 'دفع حوالة مالية',
      'money-transfer-delete': 'إلغاء حوالة مالية',
      'money-transfer-update': 'تعديل حوالة مالية',
      'name-must-be-4-names': 'ادخل الاسم الرباعي',
      'new-client': 'إضافة عميل جديد',
      'news': 'الاخبار',
      'next': 'التالي',
      'no': 'لا',
      'no-data-found': 'لا توجد بيانات',
      'no-notification-yet': 'لايوجد اشعارات!',
      'not-confirmed': 'غير معروف',
      'notes': 'ملاحظات',
      'notifications': 'الاشعارات',
      'no-transactions-yet': 'لا توجد عمليات',
      'no-trans-yet': 'لاتوجد عمليات !',
      'numbers-only': 'ادخل ارقاماً فقط',
      'ok': 'تم',
      'operator': 'مشغل الخدمة',
      'operators': 'مشغلي الخدمات',
      'otp': 'كود التحقق OTP',
      'otp-code': 'كود التحقق OTP',
      'outstanding-transfer': 'الحوالات المعلقة',
      'package': 'الباقة',
      'package-expire-date': 'تاريخ انتهاء الباقة',
      'package-name': 'اسم الباقة',
      'package-price': 'سعر الباقة',
      'package-type': 'نوع الباقة',
      'paid-money': 'دفع حوالة مالية',
      'password': 'كلمة المرور',
      'pay': 'تسديد',
      'pay-bill': 'فوترة',
      'payment': 'تسديد',
      'pay-type': 'نوع التسديد',
      'pin-error': 'خطأ في الـ PIN',
      'pre-paid': 'دفع مسبق',
      'previous': 'السابق',
      'print-date': 'تاريخ الطباعة',
      'print-pdf': 'طباعة PDF',
      'receiver-data': 'بيانات المستلم',
      'receiver-mobile': 'رقم جوال المستلم',
      'receiver-name': 'اسم المستلم',
      'records-count': 'عدد السجلات',
      'reference-number': 'رقم المرجع',
      'ref-no': 'رقم المرجع',
      'refresh': 'تحديث البيانات',
      'refresh-every': 'تحديث البيانات لكل',
      'region': 'المنطقة',
      'remittance-number': 'رقم الحوالة',
      'rem-no': 'رقم الحوالة',
      'request-date': 'تاريخ الطلب',
      'required': 'حقل إجباري!',
      're-register-device-error':
          'يوجد جهاز آخر متصل بهذا الحساب، هل تريد استبداله ؟',
      'resend': 'إعادة الارسال',
      'sabafon': 'سبأفون',
      'same-user-id': 'لايمكنك ادخال رقمك هنا',
      'select-a-company': 'اختر شركة',
      'select-amount': 'اختر المبلغ',
      'select-an-operator': 'اختر مشغل الخدمة',
      'select-a-package': 'اختر باقة',
      'select-a-region': 'اختر منطقة',
      'select-a-currency': 'اختر العملة',
      'select-brn': 'اختر فرع',
      'select-city': 'اختر مدينة',
      'select-mobile-no-type': 'اختر نوع رقم الجوال',
      'select-package': 'اختر باقة',
      'select-package-amount': 'اختر مبلغ الباقة',
      'package-amount': 'مبلغ الباقة',
      'select-package-type': 'اختر نوع الباقة',
      'select-pay-type': 'اختر نوع التسديد',
      'sender-data': 'بيانات المرسل',
      'sender-mobile': 'رقم جوال المرسل',
      'sender-name': 'اسم المرسل',
      'send-money': 'ارسال حوالة',
      'send-remittance': 'إرسال حوالة مالية',
      'service-not-active': 'الخدمة غير مفعلة',
      'services-transaction': 'خدمات الحوالات',
      'setting': 'الضبط',
      'short-statement': 'كشف الحساب',
      'show': 'عرض',
      'show-options': 'عرض الخيارات',
      'smart-charge': 'شحن ذكي',
      'start-with': 'يجب ان يبدأ الحقل بـــ @char',
      'status': 'الحالة',
      'status-description': 'وصف الحالة',
      'subscriber-number': 'رقم المشترك',
      'sum': 'الاجمالي',
      'sum-amount': 'إجمالي المبلغ',
      'this-week': 'هذا الاسبوع',
      'to-agent': ' تحويل الى وكيل',
      'to-bank': 'تحويل الى الحساب البنكي',
      'to-bank-acc': 'تحويل الى الحساب البنكي',
      'today': 'اليوم',
      'to-mobile-number': 'رقم جوال العميل المحول له',
      'to-new-client': 'إلى عميل جديد',
      'to-register-client': 'إلى عميل مسجل',
      'total-amount': 'إجمالي المبالغ',
      'transactions': 'العمليات',
      'transfer': 'تحويل',
      'transfer-to-agent': 'التحويل إلى وكيل',
      'transfer-to-bank': 'تحويل إلى بنك',
      'trans-id': 'رقم الحوالة',
      'try': 'تجريبي',
      'try-in-app-notify': 'تجربة الاشعارات الداخلية',
      'unit': 'الوحدة',
      'to-client': 'إلى عميل',
      'update-transfer': 'تعديل حوالة مالية',
      'updating-data': 'جاري تحديث البيانات',
      'version': 'رقم الاصدار',
      'wallet-system': 'نظام المحفظة',
      'week': 'الاسبوع',
      'welcome': 'مرحباً ، ',
      'yemen-mobile': 'يمن موبايل',
      'yer': 'ريال يمني',
      'yes': 'نعم',
      'you': ' YOUيو',
      'you-must-login-first': 'يجب تسجيل الدخول أولا ً',
      'your_balance': 'رصيدك ',
      'server-conn-err': 'خطأ في الاتصال بالنظام',
      'session-end': 'انتهى وقت جلسة الدخول !',
      'unknown-error': 'خطأ غير معروف !',
      'change-password': 'تغيير كلمة المرور',
      'new-password-must-different-from-previous-one':
          'يجب أن تختلف كلمة المرور الجديدة عن السابقة',
      'old-password': 'كلمة المرور الحالية',
      'new-password': 'كلمة المرور الجديدة',
      'confirm-password': 'تأكيد كلمة المرور',
      'password-not-matched': 'كلمات المرور غير متطابقة',
      'same-passwords': 'لايمكن ان تكون كلمات المرور متساوبة',
      'change': 'تغيير',
      'tips': 'تلميحات',
      'password-instructions': 'تعليمات إنشاء كلمة المرور',
      'new-password-hint-1':
          '- طول كلمة المرور 6 خانات أو أكثر وتحتوي على حروف أو أرقام.',
      'new-password-hint-2':
          '- أن لا تكون كلمة المرور من الكلمات الموجودة في القاموس.',
      'new-password-hint-3': '- أن لا تحتوي على حروف متكررة.',
      'new-password-hint-4': '- أن لايسبق إستخدامها كحد أدنى 3 أيام.',
      'new-password-hint-5':
          '- في حالة إدخال كلمة المرور خمسة مرات بشكل خاطئ سوف يتم تجميد الحساب.',
      'more': 'أكثر',
      'account-statement': 'كشف حساب',
      'enter-dates': 'يرجى إدخال البيانات',
      'from-date': 'من تاريخ',
      'to-date': 'إلى تاريخ',
      'choose': 'إختيار',
      'choose-date': 'إختر تاريخ',
      'document-number': 'رقم الوثيقة',
      'document-type': 'نوع الوثيقة',
      'page': 'صفحة',
      'of': 'من',
      'paid-remittance': 'سند استلام حوالة',
      'receiver-thumb': 'بصمة المستلم',
      'receiver-sign': 'توقيع المستلم',
      'receiver-condition1': 'استلمت المبلغ المذكور أعلاه وفي حالة جيدة.',
      'duplicate-error': 'العملية مكررة ، يرجى المحاولة مرة أخرى لاحقاً',
      'customer-name': 'إسم العميل',
      'cash-deposit': 'إيداع نقدي',
      'received-from-prefix': 'إستلمنا من',
      'received-from-suffix': 'المحترم',
      'reg-to-customer-wallet-account-no': 'قٌيدت الى حساب المحفظة رقم',
      'search-customer': 'البحث عن عميل',
      'enter-otp': 'ادخال كود التحقق (OTP)',
      'error-when-get-mndtry-flds': 'حدث خطأ اثناء الحصول على الحقول الإجبارية',
      'contact-system-specialist': 'تواصل مع مختص النظام',
      'customer-mobile': 'رقم جوال العميل',
      'personal-information': 'البيانات الشخصية',
      'mobile-no': 'رقم الجوال',
      'full-name': 'الاسم الكامل',
      'birth-place': 'مكان الميلاد',
      'birth-date': 'تاريخ الميلاد',
      'address': 'العنوان',
      'work-information': 'بيانات العمل',
      'employer': 'جهة العمل',
      'employer-phone': 'هاتف جهة العمل',
      'id-information': 'بيانات الهوية',
      'id-number': 'رقم الهوية',
      'id-issue-place': 'مكان اصدار الهوية',
      'id-issue-date': 'تاريخ اصدار الهوية',
      'id-expire-date': 'تاريخ انتهاء الهوية',
      'attachment': 'المرفقات',
      'load-id-front-img': 'تحميل واجهة بطاقة الهوية',
      'load-id-back-img': 'تحميل خلفية بطاقة الهوية',
      'load-form-img': 'تحميل نموذج فتح الحساب',
      'nationality': 'الجنسية',
      'province': 'المحافظة',
      'social-states': 'الحالة الإجتماعية',
      'qualification': 'المؤهل',
      'specialization': 'التخصص',
      'occupation': 'الوظيفة',
      'gender': 'النوع',
      'card-type': 'نوع الهوية',
      'select-option': 'تحديد من القائمة',
      'not-all-attachments-loaded': 'يرجى تحميل جميع المرفقات للمتابعة',
      'reference-not-found': 'رقم مرجع الوثيقة غير موجود',
      'load-news-data': 'تحميل بيانات الأخبار',
      'load-fields-data': 'تحميل بيانات الحقول',
      'load-nationality-data': 'تحميل بيانات الجنسيات',
      'load-provinces-data': 'تحميل بيانات المحافظات',
      'load-social-state-data': 'تحميل بيانات الحالات الإجتماعية',
      'load-qualification-data': 'تحميل بيانات المؤهلات',
      'load-specialization-data': 'تحميل بيانات التخصصات',
      'load-occupation-data': 'تحميل بيانات الوظائف',
      'load-gender-data': 'تحميل بيانات الانواع',
      'load-id-type-data': 'تحميل بيانات انواع الهويات',
      'okay': 'حسناً',
      'subscribe-price': 'سعر الاشتراك',
      'remain-balance': 'الرصيد المتبقي',
      'expiry-date': 'تاريخ الانتهاء',
      'subscription-name': 'اسم المشترك',
      'amount-owe': 'المبلغ الذي عليكم',
      'all-rights-reserved': 'جميع الحقوق محفوظة',
      'main-services': 'الخدمات الرئيسية',
      'other-services': 'الخدمات الأخرى',
      'show-news': 'إظهار الاخبار',
      'request-time-out': 'إنتهت مهلة الإتصال',
      'server-unreachable': 'خطأ في الوصول للمصدر',
      'try-again-later': 'حاول مرة أخرى لاحقاً',
      'network-money-transfer': 'حوالة عبر شبكة',
      'network-name': 'اسم الشبكة',
      'select-network': 'اختيار من قائمة الشبكات',
      'load-rem-network-data': 'تحميل بيانات الشبكات',
      'governorate': 'المحافظة',
      'select-governorate': 'اختيار من قائمة المحافظات',
      'load-net-governorate-data': 'تحميل بيانات المحافظات',
      'select-region': 'اختيار من قائمة المناطق',
      'load-net-region-data': 'تحميل بيانات المناطق',
      'net-fee': 'عمولة الشبكة',
      'send-money-by-network': 'ارسال حوالة عبر شبكة',
      'update-money-by-network': 'تعديل حوالة عبر شبكة',
      'network-money-transfer-update': 'تعديل حوالة شبكة',
      'network-send-remittance': 'ارسال حوالة عبر شبكة',
      'error-occurred': 'حدث خطأ ما !',
      'open-balance': 'الرصيد الافتتاحي',
      'end-balance': 'رصيد نهاية الفترة',
      'remittance-report': 'تقرير الحوالات',
      'sent-remittances': 'الحوالات المرسلة',
      'payout-remittances': 'الحوالات المدفوعة',
      'user-code': 'اسم المستخدم',
      'received-remittances-report': 'تقرير الحوالات المستلمة',
      'sent-remittances-report': 'تقرير الحوالات المرسلة',
      'remember-me': 'تذكرني',
      'Note': 'الملاحظات',
      'withdraw-money-by-network': 'سحب حوالة عبر شبكة',
      'network-money-withdraw': 'سحب حوالة شبكة',
      'new-register': 'تسجيل عميل جديد',
      'refresh-lists': 'تحديث القوائم',
      'to-agent-req': 'طلب تحويل لوكيل',
      'transfer-to-agent-req': 'طلب تحويل لوكيل',
      'date-format-dd-mm-yyyy': 'التاريخ يجب ان يكون بالصيغة (DD/MM/YYYY)',
      'not-valid': 'غير صحيح',
      'check-mobile': 'البحث عن الجوال',
      'mobile-exists': 'رقم الجوال موجود',
      'mobile-not-exists': 'رقم الجوال غير موجود',
      'export-to-excel': 'تصدير الى اكسل',
      'fee-curr': 'عملة العمولة',
      'rem-curr': 'عملة الحوالة',
      'personal-id': 'بطاقة شخصية',
      'passport': 'جواز سفر',
      'cashout': 'سند صرف نقدي',
      'cashout-from-prefix': 'تم الصرف النقدي إلى',
      'cashout-from-suffix': 'المحترم، مبلغ وقدره',
      'cashout-from-customer-wallet-account-no': 'قٌيدت من حساب المحفظة رقم',
      'transfer-to-prefix': 'تم التحويل إلى',
      'transfer-to-suffix': 'المحترم، مبلغ وقدره',
      'transfer-to-customer-wallet-account-no': 'قٌيدت إلى حساب المحفظة رقم',
      'transfer-req-condition':
          '** هذه الوثيقة لن تتم الا بعد اعتماد البنك لها.',
      'add-fee': 'عمولة الوكيل الاضافية',
      'done': 'تمت',
      'error': 'لم تتم !',
      'total-amount-for-success-operation': 'اجمالي مبلغ العمليات الناجحة',
      'device-registration-complete': 'تم تسجيل الجهاز',
      'please-re-login': 'يرجى تسجيل الدخول.',
      'packages': 'باقات',
      'phone': 'الهاتف',
      'view': 'عرض',
      'view-rm': 'عرض الحوالات',
      'print': 'طباعة',
      'redundant': 'مكرر',
      'nothings': 'لا يوجد',
      'IdType': 'نوع الهوية',
      'IdType-sender': 'نوع هوية المرسل',
      'IdType-num': 'رقم الهوية',
      'IdType-num-sender': 'رقم هوية المرسل',
      'purpose-send': 'الغرض من الحوالة',
      'select-id': 'اختر نوع الهوية',
      'select-purpose': 'أختر',
      'report-deposit-withdrawal': 'تقارير السحب والايداع',
      'deposit-report': 'تقارير الايداع',
      'withdrawal-report': 'تقارير السحب',
      'view-report': "عرض التقرير",
      'reports': " التقارير",
      'account-no': 'رقم الحساب',
      'report-payments': "تقارير التسديد",
      'service-provider': "مزود الخدمة",
      'beneficiary': 'رقم المستفيد',
      'select-service-provider': "أختر مزود الخدمة",
      'payments-report': "تقرير التسديد",
      'searchByRem': 'البحث برقم الحوالة',
      'searchByName': 'البحث بالاسم',
      'searchByPhone': 'البحث عبر الجوال',
      "paid": 'دفع',
      'change-pin': 'تغيير الرقم السري PIN',
      'new-pin-must-different-from-previous-one':
          "يجب ان يكون PIN مكون من 6 ارقام مختلفة ولاتساوي PIN السابق",
      "The-numbers-are-not-valid-eq-last":
          "غير مقبول الرقم الجديد يساوي القديم ",
      "The-numbers-are-not-valid": "الارقام غير مقبولة",
      'new-pin-hint-1': "1-طوله 6 خانات",
      'new-pin-hint-2': "2-أن لايحتوي على أرقام مكررة",
      'new-pin-hint-3': "3-أن لايحتوي على أرقام متتابعة",
      "old-pin": "PIN القديم",
      "new-pin": "PIN الجديد",
      "confirm-pin": "PIN تأكيد",
      'pin-instructions': "PIN تعليمات",
      "pin-not-matched": "PIN غير متطابق",
      "idImgPassport": "صورة جواز السفر",
      "not-valid-amount": "المبلغ أكبر من الرصيد",
      'transfer-not-found': 'الحوالة غير موجوده',
      "can-not-change-pin": "لم يتم تغيير PIN",
      'This-list-cannot-be-skipped-until-the-password-ischanged':
          'لايمكن تخطي هذه القائمة حتى يتم تغيير كلمة المرور',
      "can-not-be-greater-than-30": "لايمكن ان تدخل اكثر من 30 ",
      "can-not-set-agent-num": "لايمكن ادخال رقم الوكيل",
      "sum-movement": "إجمالي الحركة",
      "email": "البريد الالكتروني",
      "call-center": "رقم التواصل",
      "about-us": "حولنا",
      "enter-transfer-inform":
          "أدخل رقم الحوالة او أسم المستلم او رقم هاتف المستلم للبحث عن الحوالة ",
      'agent-system': 'نظام الوكلاء',
      'cancel-money-by-network': "الغاء حوالة عبر الشبكة",
      "network-money-cancel": "الغاء حوالة عبر الشبكة",
      "currency": "العملة",
      'fee-addition': 'عمولة إضافية',
      "network": "الشبكة",
      "transfer-approval": "اعتماد الحوالات",
      "demand": "[طلب]",
      'accreditation-confirmation': 'هل تريد الموافقة ؟',
      "confirm-approval": "تأكيد الاعتماد",
      "confirm-approval-cancel": "تأكيد الغاء الطلب",
      "none": "لايوجد",
      "do-not-have-a-right": "الخدمة غير مفعلة",
      'search-field': 'حقل بحث',
      "financial-service": "الخدمات المالية",
      "load-financial-services": "تحميل الخدمات المالية ",
      "refresh-permissions": "تحديث الصلاحيات",
      'need-approved': 'تمت بنجاح ولم يتبقى سوى اعتمادها',
      'bulk-approval': 'اعتماد تحويل جماعي',
      "internal-reference": "رقم المرجع الداخلي",
      "commission-report": "تقارير العمولات",
      "sending": "قيد الارسال",
      "continue": "هل تريد الاستمرار؟",
      "get-trans-num": "سيتم إنزال الحوالة رقم ",
      "get-proccess-num": "سيتم إنزال العملية رقم ",
      "try-again": "حاول مرة اخرى ",
      "get-data-error": "حدث خطأ عند جلب البيانات",
      "pay-number": "رقم العملية",
      "receipt-payments": "إيصال سداد",
      "according-to-this-receipt":
          "بموجب هذا الايصال تم تسديد رصيد/ باقة / دفع لـ شركة",
      "for-benefit-subscriber": "لصالح المستفيد رقم",
      "receipt-hand": "وهذا الايصال بيده",
      'exchange-acc': 'التحويل بين الحسابات',
      "from-currency": "التحويل من",
      "to-currency": "التحويل الى",
      "can-change-to-same-curr": 'لايمكن التحويل الى نفس العملة',
      "amount-want-exchange": 'المبلغ المراد تحويلة',
      "amount-exchanged": 'المبلغ المحول',
    };
  }
}
